codecov:
  branch: master
  branch: integration
  branch: 1.0.0-dev
  notify:
    after_n_builds: null
    countdown: null
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 0.5%
      project: yes
      patch: yes
      changes: yes
  
  notify:
    slack:
      default:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"
        only_pulls: null
        message: null
        flags: null
        paths: null

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  require_changes: yes
  behavior: default
